# For use with Github Actions to override plantuml execution.
---
INHERIT: mkdocs_local.yml
markdown_extensions:
  # Need one to make Inherit work O.K.
  mdx_truly_sane_lists:
  plantuml_markdown:
    plantuml_cmd: 'java -Djava.awt.headless=true -jar plantuml.jar'
    # backstage seems to block svg, so set to png for Backstage
    format: png
