# For use with Github Actions to override plantuml execution.
---
INHERIT: mkdocs_local.yml
markdown_extensions:
  # Need one to make Inherit work O.K.
  mdx_truly_sane_lists:
  plantuml_markdown:
    format: png
    base_dir: !relative
    plantuml_cmd: 'java -DPLANTUML_SECURITY_PROFILE=UNSECURE -DPLANTUML_LIMIT_SIZE=8192 -Dplantuml.include.path="docs/Projects:docs/assets/plantuml:docs" -Djava.awt.headless=true -jar plantuml.jar -config docs/assets/plantuml/config.cfg'

plugins:
  - blog:
      draft: false