@startuml (id=MEASUREMENT_PROCESS)
title
= The Measurement Process
end title

!include style.ipuml

left to right direction

person "Decision\nMaker" as DM
database History
collections Reports
frame "Metrics" as Metrics
control "Measurements" as Measurements
node "System under\nObservation" as SUO {
  portout Signal
}

Reports )--> DM: Display
Metrics )--> Reports: Collect
Metrics )-> History: Store
Measurements )--> Metrics: Compute
Signal )--> Measurements: Observe\n&\nSample

@enduml