@startuml (id=MEASUREMENT_PROCESS)
title
= The Measurement Process
end title

!include style.ipuml

person "Decision\nMaker" as DM
database History
collections Reports
frame "Metrics" as Metrics
control Measurements
node "System under\nObservation" as SUO {
  port Signal
}

DM <--( Reports: Display
Reports <--( Metrics: Collect
Metrics <-> History: store
Metrics <--( Measurements: Compute
Measurements <--( Signal: Observe and Sample
@enduml