authors:
  mpinilla:
    name: Dr. Miguel Pinilla
    description: |
      I am fascinated by the value that can be unlocked by solving problems where the physical and 
      information worlds of operations, manufacturing and supply chains intersect, where I have spent most
      of my career and my education years.
    url: https://www.linkedin.com/in/mpinilla
    avatar: https://media.licdn.com/dms/image/D5603AQH-S_E-yXo6Ew/profile-displayphoto-shrink_200_200/0/1677006323788?e=1707955200&v=beta&t=iKcr53eYO5PgAVO_hlhXAg7NwjqNILCd69kfQvW5zXM
    slug: miguel-pinilla
  mpinilla-long:
    name: Miguel Pinilla
    description: |
      With over 20 years of experience in leading technical organizations, I am a passionate and 
      innovative product and technology leader in the supply chain and automation industry. 

      My core competencies include global leadership in enterprise and supply chain systems, 
      logistics and manufacturing operations. I have a proven track record of bringing to market 
      cutting-edge products that solve complex problems and create value for customers and stakeholders. 
      I also mentor and build high-performance technical teams that follow agile practices and deliver
      quality results. 
      
      As a Fulbright Scholar and a holder of multiple patents and publications, I have a strong academic 
      and research background that informs my strategic and creative thinking.
    url: www.linkedin.com/in/mpinilla
    avatar: https://media.licdn.com/dms/image/D5603AQH-S_E-yXo6Ew/profile-displayphoto-shrink_200_200/0/1677006323788?e=1707955200&v=beta&t=iKcr53eYO5PgAVO_hlhXAg7NwjqNILCd69kfQvW5zXM
    slug: miguel-pinilla-long
    